"""Column names for the enriched hourly-emissions data contract."""

LOCAL_STANDARD_DATE_COL = "local_standard_date"
LOCAL_STANDARD_HOUR_COL = "local_standard_hour"
EMISSIONS_HOUR_UTC_COL = "emissions_hour_utc"
TIME_ZONE_COL = "time_zone"
UTC_STANDARD_OFFSET_HOURS_COL = "utc_standard_offset_hours"
FACILITY_NAMEPLATE_CAPACITY_MW_COL = "facility_nameplate_capacity_mw"
GENERATOR_CAPACITY_UNIT_COUNT_COL = "generator_capacity_unit_count"
GENERATOR_CAPACITY_COVERED_UNIT_COUNT_COL = "generator_capacity_covered_unit_count"
GENERATOR_CAPACITY_MISSING_UNIT_COUNT_COL = "generator_capacity_missing_unit_count"
GENERATOR_CAPACITY_MALFORMED_UNIT_COUNT_COL = "generator_capacity_malformed_unit_count"
GENERATOR_CAPACITY_CONFLICT_COUNT_COL = "generator_capacity_conflict_count"
TOTAL_NAMEPLATE_CAPACITY_MW_COL = "total_nameplate_capacity_mw"
NAMEPLATE_CAPACITY_COVERAGE_RATE_COL = "nameplate_capacity_coverage_rate"
