"""Column names for the enriched hourly-emissions data contract."""

LOCAL_STANDARD_DATE_COL = "local_standard_date"
LOCAL_STANDARD_HOUR_COL = "local_standard_hour"
EMISSIONS_HOUR_UTC_COL = "emissions_hour_utc"
TIME_ZONE_COL = "time_zone"
UTC_STANDARD_OFFSET_HOURS_COL = "utc_standard_offset_hours"
FACILITY_NAMEPLATE_CAPACITY_MW_COL = "facility_nameplate_capacity_mw"
FACILITY_NAMEPLATE_CAPACITY_COVERAGE_RATE_COL = "facility_nameplate_capacity_coverage_rate"
TOTAL_NAMEPLATE_CAPACITY_MW_COL = "total_nameplate_capacity_mw"
NAMEPLATE_CAPACITY_COVERAGE_RATE_COL = "nameplate_capacity_coverage_rate"
